# Generated by Django 4.2.2 on 2023-07-05 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='similaire',
            field=models.CharField(default='blanc'),
        ),
        migrations.AddField(
            model_name='produit',
            name='type',
            field=models.CharField(default='pagne'),
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('orders', models.ManyToManyField(to='shop.order')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produit'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(default='', max_length=128)),
                ('ville', models.CharField(default='', max_length=256)),
                ('rue', models.CharField(default='', max_length=256)),
                ('date_commande', models.DateTimeField(auto_now=True)),
                ('commandes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.panier')),
            ],
        ),
    ]
