# Generated by Django 4.2.2 on 2023-06-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='similaire',
            field=models.CharField(default='blanc'),
        ),
    ]
