# Generated by Django 4.2.2 on 2023-07-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_produit_similaire_produit_type_panier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='tel',
            field=models.IntegerField(default=111111),
            preserve_default=False,
        ),
    ]
