# Generated by Django 4.2.2 on 2023-07-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commande_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='tel',
            field=models.IntegerField(null=True),
        ),
    ]
