# Generated by Django 4.2.2 on 2023-07-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_commande_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='pays',
            field=models.CharField(default='Burkina Faso', max_length=128),
        ),
        migrations.AlterField(
            model_name='commande',
            name='rue',
            field=models.CharField(default='zogona', max_length=256),
        ),
        migrations.AlterField(
            model_name='commande',
            name='tel',
            field=models.IntegerField(default=60128168),
        ),
        migrations.AlterField(
            model_name='commande',
            name='ville',
            field=models.CharField(default='Ouagadougou', max_length=256),
        ),
    ]
