# Generated by Django 4.2.2 on 2023-07-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_commande_pays_alter_commande_rue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='commandes',
        ),
        migrations.AddField(
            model_name='commande',
            name='commandes',
            field=models.ManyToManyField(to='shop.panier'),
        ),
    ]
