# Generated by Django 4.2.2 on 2023-07-06 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0006_remove_commande_commandes_commande_commandes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='commandes',
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL),
        ),
    ]
