# Generated by Django 4.2.2 on 2023-07-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_produit_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='slug',
        ),
    ]
