# Generated by Django 4.2.2 on 2023-07-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_commande_commandes_commande_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='user',
        ),
        migrations.AddField(
            model_name='commande',
            name='commandes',
            field=models.ManyToManyField(to='shop.panier'),
        ),
    ]
