# Generated by Django 4.2.2 on 2023-07-07 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_remove_commande_user_commande_commandes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lignecommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='panier',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='panier',
            name='user',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='commandes',
        ),
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='commmande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.commande'),
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.produit'),
        ),
    ]
