# Generated by Django 4.2.2 on 2023-07-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_produit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
