# Generated by Django 4.2.2 on 2023-07-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_lignecommande_remove_panier_orders_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lignecommande',
            old_name='commmande',
            new_name='command',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_commande',
        ),
        migrations.AddField(
            model_name='lignecommande',
            name='date_commande',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
