# Generated by Django 4.2.2 on 2023-07-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_produit_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='produit',
            new_name='article',
        ),
    ]
